// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC4PGNld6qQ6OBoO1JpsGdIww2O78Z8bo',
    appId: '1:483456372206:web:e8e4a9b67706c67f2152ff',
    messagingSenderId: '483456372206',
    projectId: 'mapa-gabinetes-hlcamadora',
    authDomain: 'mapa-gabinetes-hlcamadora.firebaseapp.com',
    storageBucket: 'mapa-gabinetes-hlcamadora.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiIJ8k1r8q8yA457ev_JS8Ui54QGToMzc',
    appId: '1:483456372206:android:e3db4645241df0562152ff',
    messagingSenderId: '483456372206',
    projectId: 'mapa-gabinetes-hlcamadora',
    storageBucket: 'mapa-gabinetes-hlcamadora.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf8TWs2eYvP6OBtBolKqpSirbvzodM9ms',
    appId: '1:483456372206:ios:b32b796aa3e7ff1e2152ff',
    messagingSenderId: '483456372206',
    projectId: 'mapa-gabinetes-hlcamadora',
    storageBucket: 'mapa-gabinetes-hlcamadora.firebasestorage.app',
    iosBundleId: 'com.byronsd.mapaGabinetes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf8TWs2eYvP6OBtBolKqpSirbvzodM9ms',
    appId: '1:483456372206:ios:b32b796aa3e7ff1e2152ff',
    messagingSenderId: '483456372206',
    projectId: 'mapa-gabinetes-hlcamadora',
    storageBucket: 'mapa-gabinetes-hlcamadora.firebasestorage.app',
    iosBundleId: 'com.byronsd.mapaGabinetes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC4PGNld6qQ6OBoO1JpsGdIww2O78Z8bo',
    appId: '1:483456372206:web:0b3f7727418edae52152ff',
    messagingSenderId: '483456372206',
    projectId: 'mapa-gabinetes-hlcamadora',
    authDomain: 'mapa-gabinetes-hlcamadora.firebaseapp.com',
    storageBucket: 'mapa-gabinetes-hlcamadora.firebasestorage.app',
  );
}
